name: ba-leon-koth
version:             0.0.0.1
author:              "Leon Koth"
maintainer:          "leon.koth <at> stud.uni-due.de"

extra-source-files:
- README.md

extra-source-files: []
dependencies:
  - base
  - extra
  - parsec
  - template-haskell
  - containers
  - text
  - ghc
  - ghc-paths
  - directory
  - filepath
  - time
default-extensions:
  - TupleSections
  - DuplicateRecordFields
  - OverloadedLabels
  - MultiParamTypeClasses
  - FlexibleInstances
  - TypeApplications
  - ScopedTypeVariables
library:
  source-dirs: src
  exposed-modules:
    - Task
    - Fileloader
    - Default
    - DefaultSnippets
    - Inter
    - Postprocessor
    - Seed
    - Snippet
  ghc-options:
    - -Wall
    - -Werror
executables:
  generate-tasks:
    main: default.hs
    source-dirs: app
    dependencies:
      - ba-leon-koth
tests:
  ba-leon-koth-test:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ba-leon-koth
      - hspec
      - random
      - array
      - base
      - ghc
      - ghc-paths
      - ghc-boot-th
      - directory
      - random
      - QuickCheck
      - hspec
      - HUnit
      - haskell-src-exts
      - syb
      - deepseq
      - IOTasks
      - dynamic-environment
      - transparent-terms
