name: ba-leon-koth
extra-source-files: []
dependencies:
  - base
  - extra
  - parsec
  - template-haskell
  - containers
  - text
  - ghc
  - ghc-paths
  - directory
  - filepath
  - time
  - random
  - QuickCheck
default-extensions:
  - TupleSections
  - DuplicateRecordFields
  - OverloadedLabels
  - MultiParamTypeClasses
  - FlexibleInstances
  - TypeApplications
  - ScopedTypeVariables
library:
  source-dirs: src
  exposed-modules:
    - Task
    - Fileloader
  ghc-options:
    - -Wall
    - -Werror
executables:
  default:
    main: default.hs
    source-dirs: app
    dependencies:
      - ba-leon-koth
tests:
  ba-leon-koth-test:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ba-leon-koth
      - hspec
      - random
      - array
